---
output:
  pdf_document: default
  html_document: default
---
```{r 1}
Students <- c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
preTest <- c(55, 54, 47, 57, 51, 61, 57, 54, 63, 58)
postTest <- c(61, 60, 56, 63, 56, 63, 59, 56, 62, 61)

StudentScore <- data.frame(Student = Students, PreTest = preTest, Post_Test = postTest)
print(StudentScore)

#a.
if (!requireNamespace("Hmisc", quietly = TRUE)) {
  install.packages("Hmisc")
}

if (!requireNamespace("pastecs", quietly = TRUE)) {
  install.packages("pastecs")
}

library(Hmisc)
library(pastecs)

```

```{r 2}
 
# Your data
fertilizerLevels <- c(10, 10, 10, 20, 20, 50, 10, 20, 10, 50, 20, 50, 20, 10)

# Converts to ordered factor
orderedFertilizer <- factor(fertilizerLevels, levels = c(10, 20, 50), ordered = TRUE)

# Prints the result
print("Original Data:")
print(fertilizerLevels)
print("Ordered Factor:")
print(orderedFertilizer)

```

```{r 3}

#You can employ a factor to depict the levels experienced by 10 individuals.

ExrLvl <- c("l", "n", "n", "i", "l", "l", "n", "n", "i", "l")

ExrFact <- factor(ExrLvl, levels = c("n", "l", "i"), labels = c("none", "light", "intense"))

print(ExrFact)
```

```{r 4}
State <- c("tas", "sa", "qld", "nsw", "nsw", "nt", "wa", "wa", "qld",
           "vic", "nsw", "vic", "qld", "qld", "sa", "tas", "sa", "nt",
           "wa", "vic", "qld", "nsw", "nsw", "wa", "sa", "act", "nsw",
           "vic", "vic", "act")
#a. 
StateFactor<- factor(State)
print(StateFactor)
#The results offer the various "Levels" presented in the vector.
```

```{r 5}

Income <- c(60, 49, 40, 61, 64, 60, 59, 54,
             62, 69, 70, 42, 56, 61, 61, 61, 58, 51, 48,
             65, 49, 49, 41, 48, 52, 46, 59, 46, 58, 43)
#a. Mean Sample

incMeans <- tapply(Income, StateFactor, mean)
print(incMeans)

#b. The results show the mean for each state provided 
```

```{r 6}
#stdError <- function(x) sqrt(var(x)/length(x))
#incSter <- tapply(Income, statef, stdError)

#a. The standard error is that the object 'statef' is not found as the vector was named as 'state'.
```
```{r 7}
install.packages("titanic")
library(titanic)
data("titanic_train")
titanicData <- titanic_train


Survived <- subset(titanicData, Survived == 1)
NotSurvived <- subset(titanicData, Survived == 0)

print(Survived)
print(NotSurvived)

```

```{r 8}
install.packages("readr")
library(readr)
breastcancerWisconsin <- read_csv("/cloud/project/Rworksheet6/breastcancer_wisconsin.csv")
print(breastcancerWisconsin)

#a. The dataset is focused on the documented details pertaining to individuals who have breast cancer and their related features.


```

``` {r 9}
library(xlsx)
abalone<- read.csv("/cloud/project/Rworksheet6/abalone.csv")
xlsx::write.xlsx(abalone, "abalone.xls", col.names=TRUE, row.names=TRUE, sheetName="sample")
library("AppliedPredictiveModeling")
head(abalone)
summary(abalone)
```